FROM ubuntu:23.04
RUN apt update --fix-missing
RUN apt install -y nala

RUN nala install -y git
RUN nala install -y cmake
RUN nala install -y ninja-build
RUN nala install -y gcc-13 g++-13

# dependencies
RUN nala install -y libssl-dev
RUN nala install -y libbrotli-dev
RUN nala install -y zlib1g-dev

ENV CC=gcc-13
ENV CXX=g++-13

ADD ./src /build/src
COPY ./cmake /build/cmake
COPY CMakeLists.txt /build

WORKDIR /build/build
RUN cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ../
RUN cmake --build ./

WORKDIR /app
RUN cp /build/build/supreme-octopus /app/app
ENTRYPOINT ["/app/app"]
